apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-otel-config
  labels:
    app: petclinic
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://<yourname>-k8s-monitoring-alloy.<yourname>-k8smonitoring.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "petclinic"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev,service.namespace=<yourname>-java-app,service.version=1.0.0"